//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportReceiptDetail
    {
        public int ResellerId { get; set; }
        public int PhoneId { get; set; }
        public int ExportReceiptId { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
    
        public virtual ExportReceipt ExportReceipt { get; set; }
        public virtual Phone Phone { get; set; }
        public virtual Reseller Reseller { get; set; }
    }
}
