//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinalDatabaseEntities : DbContext
    {
        public FinalDatabaseEntities()
            : base("name=FinalDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Accountant> Accountants { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<DeliveryStatu> DeliveryStatus { get; set; }
        public virtual DbSet<ExportReceipt> ExportReceipts { get; set; }
        public virtual DbSet<ExportReceiptDetail> ExportReceiptDetails { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<ReceiptDetail> ReceiptDetails { get; set; }
        public virtual DbSet<Reseller> Resellers { get; set; }
        public virtual DbSet<ResellerImportReceipt> ResellerImportReceipts { get; set; }
        public virtual DbSet<ResellerImportReceiptDetail> ResellerImportReceiptDetails { get; set; }
        public virtual DbSet<ResellerStorage> ResellerStorages { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<WarehouseProduct> WarehouseProducts { get; set; }
    }
}
