//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phone()
        {
            this.ExportReceiptDetails = new HashSet<ExportReceiptDetail>();
            this.ReceiptDetails = new HashSet<ReceiptDetail>();
            this.ResellerImportReceiptDetails = new HashSet<ResellerImportReceiptDetail>();
            this.ResellerStorages = new HashSet<ResellerStorage>();
            this.WarehouseProducts = new HashSet<WarehouseProduct>();
        }
    
        public int PhoneId { get; set; }
        public string PhoneName { get; set; }
        public string PhoneDescription { get; set; }
        public int PhoneYear { get; set; }
        public string Image { get; set; }
        public int Price { get; set; }
        public int ManufacturerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportReceiptDetail> ExportReceiptDetails { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptDetail> ReceiptDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResellerImportReceiptDetail> ResellerImportReceiptDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResellerStorage> ResellerStorages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseProduct> WarehouseProducts { get; set; }
    }
}
